// GENERATED CODE - 由 tool/gen_settings_index.dart 生成，请勿手工编辑。
// 重新生成：dart tool/gen_settings_index.dart

import 'package:pure_live/modules/settings/pages/settings_search_entry.dart';
import 'package:pure_live/modules/live_play/widgets/keyword_block_page.dart';
import 'package:pure_live/modules/settings/pages/audience_metric_settings_page.dart';
import 'package:pure_live/modules/settings/pages/cache_data_settings_page.dart';
import 'package:pure_live/modules/settings/pages/font_and_text_page.dart';
import 'package:pure_live/modules/settings/pages/font_family_manager_page.dart';
import 'package:pure_live/modules/settings/pages/font_settings_page.dart';
import 'package:pure_live/modules/settings/pages/general_settings_page.dart';
import 'package:pure_live/modules/settings/pages/language_settings_page.dart';
import 'package:pure_live/modules/settings/pages/loading_style_settings_page.dart';
import 'package:pure_live/modules/settings/pages/local_config_preveiw.dart';
import 'package:pure_live/modules/settings/pages/local_interaction_settings_page.dart';
import 'package:pure_live/modules/settings/pages/navigation_settings_page.dart';
import 'package:pure_live/modules/settings/pages/network_proxy_settings_page.dart';
import 'package:pure_live/modules/settings/pages/page_settings.dart';
import 'package:pure_live/modules/settings/pages/pip_danmaku_settings_page.dart';
import 'package:pure_live/modules/settings/pages/platform_settings_page.dart';
import 'package:pure_live/modules/settings/pages/player_kernel_settings_page.dart';
import 'package:pure_live/modules/settings/pages/refresh_settings.dart';
import 'package:pure_live/modules/settings/pages/theme_settings_page.dart';
import 'package:pure_live/modules/settings/pages/video_settings_page.dart';

/// 自动生成的设置搜索索引：(条目标题 i18n key, 分组 i18n key, 页面构造)。
class GeneratedSettingsSearchIndex {
  GeneratedSettingsSearchIndex._();

  static const List<SettingsSearchEntry> entries = [
    SettingsSearchEntry('anime4k_super_resolution', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('anime4k_super_resolution_subtitle', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('asmr_sleep_mode', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('asmr_sleep_mode_desc', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('asmr_sleep_timer', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('asmr_sleep_timer_desc', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('audience_metric_settings', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('audience_metric_settings', 'audience_metric_settings', const AudienceMetricSettingsPage()),
    SettingsSearchEntry('audience_metric_settings_desc', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('audience_mode_heat', 'audience_metric_settings', const AudienceMetricSettingsPage()),
    SettingsSearchEntry('audience_mode_heat_desc', 'audience_metric_settings', const AudienceMetricSettingsPage()),
    SettingsSearchEntry('audience_mode_online', 'audience_metric_settings', const AudienceMetricSettingsPage()),
    SettingsSearchEntry('audience_mode_online_desc', 'audience_metric_settings', const AudienceMetricSettingsPage()),
    SettingsSearchEntry('audio_only_mode', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('audio_only_mode_subtitle', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('audio_output_driver', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('auto_refresh_follow', 'refresh_settings', const RefreshSettingsPage()),
    SettingsSearchEntry('auto_refresh_follow_subtitle', 'refresh_settings', const RefreshSettingsPage()),
    SettingsSearchEntry('auto_refresh_interval', 'refresh_settings', const RefreshSettingsPage()),
    SettingsSearchEntry('auto_refresh_thumbnails', 'refresh_settings', const RefreshSettingsPage()),
    SettingsSearchEntry('auto_refresh_thumbnails_subtitle', 'refresh_settings', const RefreshSettingsPage()),
    SettingsSearchEntry('blocked_danmaku_users', 'settings', const KeywordBlockPage()),
    SettingsSearchEntry('blocked_gifts_in_room', 'settings', const KeywordBlockPage()),
    SettingsSearchEntry('cache_and_data', 'cache_and_data', const CacheDataSettingsPage()),
    SettingsSearchEntry('cdn_speed_test', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('cdn_speed_test_subtitle', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('change_font_family', 'font_text_settings', const FontAndTextPage()),
    SettingsSearchEntry('change_loading_color', 'change_loading_style', const LoadingStyleSettingsPage()),
    SettingsSearchEntry('change_loading_color_subtitle', 'change_loading_style', const LoadingStyleSettingsPage()),
    SettingsSearchEntry('change_loading_style', 'change_loading_style', const LoadingStyleSettingsPage()),
    SettingsSearchEntry('change_loading_style', 'theme_customization', const ThemeSettingsPage()),
    SettingsSearchEntry('change_loading_style_subtitle', 'theme_customization', const ThemeSettingsPage()),
    SettingsSearchEntry('change_player', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('change_theme_color', 'theme_customization', const ThemeSettingsPage()),
    SettingsSearchEntry('change_theme_color_subtitle', 'theme_customization', const ThemeSettingsPage()),
    SettingsSearchEntry('change_theme_mode', 'theme_customization', const ThemeSettingsPage()),
    SettingsSearchEntry('change_theme_mode_subtitle', 'theme_customization', const ThemeSettingsPage()),
    SettingsSearchEntry('clear_all_cache', 'cache_and_data', const CacheDataSettingsPage()),
    SettingsSearchEntry('clear_all_cache_meida_desc', 'cache_and_data', const CacheDataSettingsPage()),
    SettingsSearchEntry('compat_mode', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('compat_mode_subtitle', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('confirm_clear_cache', 'cache_and_data', const CacheDataSettingsPage()),
    SettingsSearchEntry('countdown_duration', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('cross_axis_spacing', 'theme_customization', const ThemeSettingsPage()),
    SettingsSearchEntry('cross_axis_spacing_subtitle', 'theme_customization', const ThemeSettingsPage()),
    SettingsSearchEntry('current_cache_size', 'cache_and_data', const CacheDataSettingsPage()),
    SettingsSearchEntry('custom_output_hwdec', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('danmaku_area', 'pip_danmaku', const PipDanmakuSettingsPage()),
    SettingsSearchEntry('danmaku_fps', 'pip_danmaku', const PipDanmakuSettingsPage()),
    SettingsSearchEntry('danmaku_no_emoji', 'pip_danmaku', const PipDanmakuSettingsPage()),
    SettingsSearchEntry('desktop_default_volume', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('enable_app_proxy', 'network_proxy_settings', const NetworkProxySettingsPage()),
    SettingsSearchEntry('enable_app_proxy_desc', 'network_proxy_settings', const NetworkProxySettingsPage()),
    SettingsSearchEntry('enable_auto_check_update', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('enable_background_play', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('enable_background_play_subtitle', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('enable_codec', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('enable_countdown_close', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('enable_countdown_close_subtitle', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('enable_dynamic_color', 'theme_customization', const ThemeSettingsPage()),
    SettingsSearchEntry('enable_dynamic_color_subtitle', 'theme_customization', const ThemeSettingsPage()),
    SettingsSearchEntry('enable_fullscreen_default', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('enable_fullscreen_default_subtitle', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('enable_player_proxy', 'network_proxy_settings', const NetworkProxySettingsPage()),
    SettingsSearchEntry('enable_player_proxy', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('enable_player_proxy_desc', 'network_proxy_settings', const NetworkProxySettingsPage()),
    SettingsSearchEntry('enable_screen_keep_on', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('enable_screen_keep_on_subtitle', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('esports_reminder_lead', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('esports_reminder_lead_subtitle', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('exit_action', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('exit_action_exit', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('exit_action_minimize', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('exit_float_window', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('exit_float_window_subtitle', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('factory_default_desc', 'settings', const FontFamilyManagerPage()),
    SettingsSearchEntry('font_auto_weight', 'settings', const FontFamilyManagerPage()),
    SettingsSearchEntry('font_auto_weight_desc', 'settings', const FontFamilyManagerPage()),
    SettingsSearchEntry('font_body_large_title', 'font_settings_title', const FontSettingsPage()),
    SettingsSearchEntry('font_body_medium_title', 'font_settings_title', const FontSettingsPage()),
    SettingsSearchEntry('font_body_small_title', 'font_settings_title', const FontSettingsPage()),
    SettingsSearchEntry('font_lock_weight', 'settings', const FontFamilyManagerPage()),
    SettingsSearchEntry('font_lock_weight_desc', 'settings', const FontFamilyManagerPage()),
    SettingsSearchEntry('font_settings_desc', 'font_text_settings', const FontAndTextPage()),
    SettingsSearchEntry('font_settings_title', 'font_settings_title', const FontSettingsPage()),
    SettingsSearchEntry('font_settings_title', 'font_text_settings', const FontAndTextPage()),
    SettingsSearchEntry('font_size', 'pip_danmaku', const PipDanmakuSettingsPage()),
    SettingsSearchEntry('font_text_settings', 'font_text_settings', const FontAndTextPage()),
    SettingsSearchEntry('font_title_large_title', 'font_settings_title', const FontSettingsPage()),
    SettingsSearchEntry('font_title_medium_title', 'font_settings_title', const FontSettingsPage()),
    SettingsSearchEntry('font_weight', 'pip_danmaku', const PipDanmakuSettingsPage()),
    SettingsSearchEntry('force_destroy_player', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('force_destroy_player_subtitle', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('fullscreen_gift_card_opacity', 'local_interaction_settings', const LocalInteractionSettingsPage()),
    SettingsSearchEntry('fullscreen_sc_opacity', 'local_interaction_settings', const LocalInteractionSettingsPage()),
    SettingsSearchEntry('general', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('global_mute', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('global_mute_subtitle', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('gpu_decode', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('gravity_auto_fullscreen', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('gravity_auto_fullscreen_subtitle', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('hardware_decoder', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('high_refresh_rate', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('kernel_switch', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('kernel_switch_subtitle', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('keyword_added_count', 'settings', const KeywordBlockPage()),
    SettingsSearchEntry('language_settings', 'language_settings', const LanguageSettingsPage()),
    SettingsSearchEntry('live_buffer_size', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('live_buffer_size_subtitle', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('local_config_preview', 'local_config_preview', const LocalConfigPreviewPage()),
    SettingsSearchEntry('local_gift_effects', 'local_interaction_settings', const LocalInteractionSettingsPage()),
    SettingsSearchEntry('local_gift_effects_desc', 'local_interaction_settings', const LocalInteractionSettingsPage()),
    SettingsSearchEntry('local_interaction_enable', 'local_interaction_settings', const LocalInteractionSettingsPage()),
    SettingsSearchEntry('local_interaction_enable_desc', 'local_interaction_settings', const LocalInteractionSettingsPage()),
    SettingsSearchEntry('local_interaction_settings', 'local_interaction_settings', const LocalInteractionSettingsPage()),
    SettingsSearchEntry('local_interaction_status', 'local_interaction_settings', const LocalInteractionSettingsPage()),
    SettingsSearchEntry('local_overlay_message', 'local_interaction_settings', const LocalInteractionSettingsPage()),
    SettingsSearchEntry('local_overlay_message_desc', 'local_interaction_settings', const LocalInteractionSettingsPage()),
    SettingsSearchEntry('local_show_level_badge', 'local_interaction_settings', const LocalInteractionSettingsPage()),
    SettingsSearchEntry('local_show_level_badge_desc', 'local_interaction_settings', const LocalInteractionSettingsPage()),
    SettingsSearchEntry('local_show_platform_badge', 'local_interaction_settings', const LocalInteractionSettingsPage()),
    SettingsSearchEntry('local_show_platform_badge_desc', 'local_interaction_settings', const LocalInteractionSettingsPage()),
    SettingsSearchEntry('main_axis_spacing', 'theme_customization', const ThemeSettingsPage()),
    SettingsSearchEntry('main_axis_spacing_subtitle', 'theme_customization', const ThemeSettingsPage()),
    SettingsSearchEntry('max_concurrent_refresh', 'refresh_settings', const RefreshSettingsPage()),
    SettingsSearchEntry('mobile_default_volume', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('mobile_quality', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('mobile_quality_subtitle', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('navigation_display_settings', 'navigation_display_settings', const NavigationSettingsPage()),
    SettingsSearchEntry('network_proxy', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('network_proxy_settings', 'network_proxy_settings', const NetworkProxySettingsPage()),
    SettingsSearchEntry('network_proxy_subtitle', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('no_exit_confirm', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('opacity', 'pip_danmaku', const PipDanmakuSettingsPage()),
    SettingsSearchEntry('page_settings', 'page_settings', const PageSettingsPage()),
    SettingsSearchEntry('page_settings', 'theme_customization', const ThemeSettingsPage()),
    SettingsSearchEntry('page_settings_subtitle', 'theme_customization', const ThemeSettingsPage()),
    SettingsSearchEntry('page_size_options_manage', 'page_settings', const PageSettingsPage()),
    SettingsSearchEntry('pip_danmaku', 'pip_danmaku', const PipDanmakuSettingsPage()),
    SettingsSearchEntry('pip_danmaku_auto_scale', 'pip_danmaku', const PipDanmakuSettingsPage()),
    SettingsSearchEntry('pip_danmaku_enable', 'pip_danmaku', const PipDanmakuSettingsPage()),
    SettingsSearchEntry('pip_danmaku_interval', 'pip_danmaku', const PipDanmakuSettingsPage()),
    SettingsSearchEntry('pip_danmaku_max_visible', 'pip_danmaku', const PipDanmakuSettingsPage()),
    SettingsSearchEntry('pip_danmaku_original_color', 'pip_danmaku', const PipDanmakuSettingsPage()),
    SettingsSearchEntry('pip_danmaku_reset', 'pip_danmaku', const PipDanmakuSettingsPage()),
    SettingsSearchEntry('platform_display', 'platform_settings', const PlatformSettingsPage()),
    SettingsSearchEntry('platform_display_subtitle', 'platform_settings', const PlatformSettingsPage()),
    SettingsSearchEntry('platform_settings', 'platform_settings', const PlatformSettingsPage()),
    SettingsSearchEntry('player_kernel_settings', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('prefer_hevc', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('prefer_hevc_subtitle', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('prefer_platform', 'platform_settings', const PlatformSettingsPage()),
    SettingsSearchEntry('prefer_resolution', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('prefer_resolution_cellular', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('prefer_resolution_subtitle', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('proxy_settings', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('refresh_loading', 'theme_customization', const ThemeSettingsPage()),
    SettingsSearchEntry('refresh_settings', 'refresh_settings', const RefreshSettingsPage()),
    SettingsSearchEntry('refresh_thumbnails', 'cache_and_data', const CacheDataSettingsPage()),
    SettingsSearchEntry('refresh_thumbnails_desc', 'cache_and_data', const CacheDataSettingsPage()),
    SettingsSearchEntry('select_countdown_duration', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('show_danmaku', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('show_danmaku_subtitle', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('show_goto_button', 'page_settings', const PageSettingsPage()),
    SettingsSearchEntry('show_goto_button_subtitle', 'page_settings', const PageSettingsPage()),
    SettingsSearchEntry('show_live_duration', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('show_live_duration_desc', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('show_page_size_selector', 'page_settings', const PageSettingsPage()),
    SettingsSearchEntry('show_page_size_selector_subtitle', 'page_settings', const PageSettingsPage()),
    SettingsSearchEntry('show_scroll_to_top', 'page_settings', const PageSettingsPage()),
    SettingsSearchEntry('show_scroll_to_top_subtitle', 'page_settings', const PageSettingsPage()),
    SettingsSearchEntry('speed', 'pip_danmaku', const PipDanmakuSettingsPage()),
    SettingsSearchEntry('splash_animation', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('splash_animation_subtitle', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('startup', 'general', const GeneralSettingsPage()),
    SettingsSearchEntry('text_size_title', 'font_text_settings', const FontAndTextPage()),
    SettingsSearchEntry('theme_customization', 'theme_customization', const ThemeSettingsPage()),
    SettingsSearchEntry('thumbnail_refresh_interval', 'refresh_settings', const RefreshSettingsPage()),
    SettingsSearchEntry('video_output_driver', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('video_settings', 'video_settings', const VideoSettingsPage()),
    SettingsSearchEntry('volume_normalization', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('volume_normalization_subtitle', 'player_kernel_settings', const PlayerKernelSettingsPage()),
    SettingsSearchEntry('windows_dynamic_refresh_rate', 'general', const GeneralSettingsPage()),
  ];
}
